### ISSUE TITLE
License

### ISSUE THREAD

**Issue by B4dT0bi** [elshobokshy/ProjectCarRacing#1]
Hi,

do you mind setting the License for your Project to MIT or at least GPL?

This would be awesome.

Currently I'm planning to use your work for a fork where an AI will drive the car ;)

And it would make things a lot easier if there is a defined license to your project.

thanks and regards,
Tobi

**Comment by Tartiflettus** [comment]
Hi!

First of all, I am happy that you are interested in this work^^
I'll see the owner this evening, so you can espect the licence published
tonight.

As indicated in the README, this project was a short school project.
We were in 2nd year, so we were not exactly good developers.
The project was more about experiencing things than follow a proper
guideline.

The point is: it probably won't the best choice for what you will be doing.
Nevertheless, we'll add a licence, so do as you prefer!

If you have questions about it, feel free to contact me (at this address),
it's a bit old now, but I think I can nevertheless dig into our code x)

Best regards


Le mar. 5 mars 2019 à 15:28, Tobias Böse <notifications@github.com> a
écrit :

**Comment by B4dT0bi** [comment]
Great thanks!

I just wanted a simple Top-down view Racing Game which was implemented in SFML, and here it is ;)

My "project" is just creating a simple simulation environment so an ai (q-learning algorithm) can be applied and aftwerwards applying the learnt to another app which will use a camera and opencv to apply some object tracking and stream all this, and i wanted to dust off my c++ skills.

So yes it might not be the best choice but for me in my current situation it is good enough.

thanks for all your work!

**Comment by elshobokshy** [comment]
I'm happy to see the project getting used by other people, feel free to share with us in this issue the result of your project if it's going to be public.

Good luck!
